name: Run integration test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to run integration test'
        required: true
        default: 'dev'

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   repository: 'nervosnetwork/mercury'
        #   ref: '${{ github.event.inputs.branch }}'
      - name: Prepare environment
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/1.5.0/hurl_1.5.0_amd64.deb
          sudo dpkg -i hurl_1.5.0_amd64.deb  # install hurl
          shopt -s globstar  # enable globstart (**)
      - name: Run integration test
        run: |
          hurl --variable mercury_testnet_host="${{ secrets.MERCURY_TESTNET_HOST }}" --test ./integration-test/**/*hurl --summary
